//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace CADService.Models
{
    public class CadJob
    {

        public int ID { get; set; }
        public int OwnerID { get; set; }
        public string LCID { get; set; }
        public short ProductID { get; set; }
        public short VersionID { get; set; }
        public short ComponentID { get; set; }
        public string Description { get; set; }
        public byte StatusID { get; set; }
        public Int32? IssueID { get; set; }
        public bool EmailNotified { get; set; }
        public DateTimeOffset? CreatedTime { get; set; }
        public DateTimeOffset? UploadStartTime { get; set; }
        public DateTimeOffset? UploadEndTime { get; set; }
        public DateTimeOffset? ParseStartTime { get; set; }
        public DateTimeOffset? ParseEndTime { get; set; }
        public DateTimeOffset? AnalyzeStartTime { get; set; }
        public DateTimeOffset? AnalyzeEndTime { get; set; }
        public string StatusMsg { get; set; }
        public DateTimeOffset? FailureTime { get; set; }

    }
}
